# Generated by Django 3.2.12 on 2023-02-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20230220_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='login_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logout_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
